#server:
 # port: 8090
#spring:
 # datasource:
 #    username: root
#    url: jdbc:mysql://localhost:3306/paradise_hotel
 #    driver-class-name: com.mysql.cj.jdbc.Driver
#
 # jpa:
  #   show-sql: true
   #  hibernate:
    #    ddl-auto: update
     #   formate_sql: true
#
 # servlet:
  #    multipart:
   #         max-file-size: 10MB
    #        max-request-size: 10MB
     #       file-size-threshold: 10KB
